// data.js — KidQuest i18n + worlds + quests + avatars
window.KQ = {
  i18n: {
    fr: {
      brand: "KidQuest",
      tagline: "L'aventure du savoir",
      // Onboarding
      welcome: "Bonjour, petit aventurier !",
      welcome_sub: "Choisis ta langue pour commencer",
      lang_fr: "Français",
      lang_en: "English",
      next: "Continuer",
      back: "Retour",
      skip: "Passer",
      choose_avatar: "Choisis ton héros !",
      choose_avatar_sub: "Tu pourras le changer plus tard",
      whats_your_name: "Comment tu t'appelles ?",
      name_placeholder: "Ton prénom",
      lets_go: "C'est parti !",
      // Home / world map
      hello_name: "Bonjour {name} !",
      world_map: "La grande carte",
      choose_world: "Choisis un monde à explorer",
      english_quest: "English Quest",
      english_sub: "Les mots magiques",
      geo_explorer: "Geo Explorer",
      geo_sub: "Voyage autour du monde",
      math_arena: "Math Arena",
      math_sub: "Les jeux des nombres",
      locked: "Verrouillé",
      coming_soon: "Bientôt disponible",
      stars_won: "{n} étoiles gagnées",
      streak_days: "{n} jours d'affilée",
      // Hub
      level: "Niveau",
      lesson: "Leçon",
      hub_english: "Le monde de l'anglais",
      hub_geo: "Le monde des explorateurs",
      hub_math: "Le monde des chiffres",
      play: "Jouer",
      replay: "Rejouer",
      // Quiz
      question_of: "Question {a} sur {b}",
      pick_answer: "Touche la bonne réponse",
      check: "Vérifier",
      correct: "Bravo !",
      wrong: "Oups, essaie encore !",
      try_again: "Essaie encore",
      continue: "Continuer",
      hint: "Un indice",
      // Reward
      well_done: "Bien joué !",
      stars_earned: "Tu gagnes {n} étoiles",
      new_badge: "Nouveau badge !",
      back_to_map: "Retour à la carte",
      // Profile
      profile: "Mon profil",
      my_collection: "Ma collection",
      trophies: "Trophées",
      streak: "Série",
      total_stars: "Total étoiles",
      levels_done: "Niveaux finis",
      day: "jour",
      days: "jours",
      // Parent
      parent_zone: "Espace parents",
      parent_lock: "Pour les grands seulement",
      parent_settings: "Réglages",
      progress: "Progression",
      difficulty: "Difficulté",
      easy: "Facile",
      medium: "Moyen",
      hard: "Difficile",
      time_today: "Temps aujourd'hui",
      minutes: "minutes",
      // Status
      done: "Fini",
      current: "Ici",
      // Footer
      footer: "Propulsé par Claude AI · Anthropic",
    },
    en: {
      brand: "KidQuest",
      tagline: "The learning adventure",
      welcome: "Hello, little adventurer!",
      welcome_sub: "Pick your language to begin",
      lang_fr: "Français",
      lang_en: "English",
      next: "Continue",
      back: "Back",
      skip: "Skip",
      choose_avatar: "Pick your hero!",
      choose_avatar_sub: "You can change it later",
      whats_your_name: "What's your name?",
      name_placeholder: "Your name",
      lets_go: "Let's go!",
      hello_name: "Hello {name}!",
      world_map: "The big map",
      choose_world: "Pick a world to explore",
      english_quest: "English Quest",
      english_sub: "Magic words",
      geo_explorer: "Geo Explorer",
      geo_sub: "Travel the world",
      math_arena: "Math Arena",
      math_sub: "Number games",
      locked: "Locked",
      coming_soon: "Coming soon",
      stars_won: "{n} stars earned",
      streak_days: "{n}-day streak",
      level: "Level",
      lesson: "Lesson",
      hub_english: "The English world",
      hub_geo: "The Explorer world",
      hub_math: "The Numbers world",
      play: "Play",
      replay: "Replay",
      question_of: "Question {a} of {b}",
      pick_answer: "Tap the right answer",
      check: "Check",
      correct: "Yay!",
      wrong: "Oops, try again!",
      try_again: "Try again",
      continue: "Continue",
      hint: "Hint",
      well_done: "Well done!",
      stars_earned: "You earn {n} stars",
      new_badge: "New badge!",
      back_to_map: "Back to map",
      profile: "My profile",
      my_collection: "My collection",
      trophies: "Trophies",
      streak: "Streak",
      total_stars: "Total stars",
      levels_done: "Levels done",
      day: "day",
      days: "days",
      parent_zone: "Parent area",
      parent_lock: "For grown-ups only",
      parent_settings: "Settings",
      progress: "Progress",
      difficulty: "Difficulty",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      time_today: "Time today",
      minutes: "minutes",
      done: "Done",
      current: "Here",
      footer: "Powered by Claude AI · Anthropic",
    },
  },

  // 12 child avatars
  avatars: [
    { id: "fox",     emoji: "🦊", color: "#FF8E53" },
    { id: "lion",    emoji: "🦁", color: "#FFD93D" },
    { id: "owl",     emoji: "🦉", color: "#A78BFA" },
    { id: "dragon",  emoji: "🐲", color: "#56C596" },
    { id: "panda",   emoji: "🐼", color: "#cbd5e1" },
    { id: "penguin", emoji: "🐧", color: "#60a5fa" },
    { id: "unicorn", emoji: "🦄", color: "#f093fb" },
    { id: "robot",   emoji: "🤖", color: "#94a3b8" },
    { id: "astro",   emoji: "🧑‍🚀", color: "#7c6ef5" },
    { id: "wizard",  emoji: "🧙", color: "#FF6B6B" },
    { id: "ninja",   emoji: "🥷", color: "#475569" },
    { id: "elf",     emoji: "🧝", color: "#FF99B6" },
  ],

  // 3 hubs with distinct identity and mascot id
  hubs: [
    {
      id: "english",
      mascot: "owl",
      mascotName: { fr: "Lumi", en: "Lumi" },
      title_key: "english_quest",
      sub_key: "english_sub",
      hub_title_key: "hub_english",
      // KidQuest teal family
      color: "#4ECDC4",
      colorDeep: "#44A9C6",
      colorSoft: "#A8E6CF",
      bgGrad: "linear-gradient(180deg, #c8f5f0 0%, #a8e6cf 100%)",
      bgGradDark: "linear-gradient(180deg, #143838 0%, #0e2a2a 100%)",
    },
    {
      id: "geo",
      mascot: "turtle",
      mascotName: { fr: "Globi", en: "Globi" },
      title_key: "geo_explorer",
      sub_key: "geo_sub",
      hub_title_key: "hub_geo",
      // Yellow/orange family
      color: "#FF8E53",
      colorDeep: "#FF6B35",
      colorSoft: "#FFD93D",
      bgGrad: "linear-gradient(180deg, #fff1d6 0%, #ffdba8 100%)",
      bgGradDark: "linear-gradient(180deg, #3a2a1a 0%, #2a1f10 100%)",
    },
    {
      id: "math",
      mascot: "fox",
      mascotName: { fr: "Pixel", en: "Pixel" },
      title_key: "math_arena",
      sub_key: "math_sub",
      hub_title_key: "hub_math",
      // Purple/pink family
      color: "#A78BFA",
      colorDeep: "#7c6ef5",
      colorSoft: "#f093fb",
      bgGrad: "linear-gradient(180deg, #ede8ff 0%, #d6cdff 100%)",
      bgGradDark: "linear-gradient(180deg, #1f1a3a 0%, #15102a 100%)",
    },
  ],

  // Per-hub level lists (8 levels each, 4-6 ans logic)
  levels: {
    english: [
      { n: 1, title_fr: "Les animaux", title_en: "Animals",   topic: "animals",   stars: 3, status: "done" },
      { n: 2, title_fr: "Les couleurs", title_en: "Colours",  topic: "colors",    stars: 3, status: "done" },
      { n: 3, title_fr: "Les chiffres", title_en: "Numbers",  topic: "numbers",   stars: 2, status: "done" },
      { n: 4, title_fr: "La famille",  title_en: "Family",    topic: "family",    stars: 0, status: "current" },
      { n: 5, title_fr: "Les fruits",  title_en: "Fruits",    topic: "fruits",    stars: 0, status: "locked" },
      { n: 6, title_fr: "Le corps",    title_en: "The body",  topic: "body",      stars: 0, status: "locked" },
      { n: 7, title_fr: "Les saisons", title_en: "Seasons",   topic: "seasons",   stars: 0, status: "locked" },
      { n: 8, title_fr: "Le défi !",   title_en: "Big quiz",  topic: "challenge", stars: 0, status: "locked", boss: true },
    ],
    geo: [
      { n: 1, title_fr: "L'Europe",        title_en: "Europe",         topic: "europe",  stars: 3, status: "done" },
      { n: 2, title_fr: "L'Afrique",       title_en: "Africa",         topic: "africa",  stars: 2, status: "done" },
      { n: 3, title_fr: "Les drapeaux",    title_en: "Flags",          topic: "flags",   stars: 0, status: "current" },
      { n: 4, title_fr: "Les capitales",   title_en: "Capitals",       topic: "capitals",stars: 0, status: "locked" },
      { n: 5, title_fr: "L'Asie",          title_en: "Asia",           topic: "asia",    stars: 0, status: "locked" },
      { n: 6, title_fr: "L'Amérique",      title_en: "The Americas",   topic: "america", stars: 0, status: "locked" },
      { n: 7, title_fr: "Les océans",      title_en: "Oceans",         topic: "oceans",  stars: 0, status: "locked" },
      { n: 8, title_fr: "Tour du monde !", title_en: "World tour",     topic: "world",   stars: 0, status: "locked", boss: true },
    ],
    math: [
      { n: 1, title_fr: "Compter jusqu'à 10", title_en: "Count to 10",  topic: "count10",  stars: 3, status: "done" },
      { n: 2, title_fr: "Plus grand, plus petit", title_en: "More or less", topic: "compare", stars: 3, status: "done" },
      { n: 3, title_fr: "Les additions",     title_en: "Add it up",     topic: "add",      stars: 2, status: "done" },
      { n: 4, title_fr: "Les formes",        title_en: "Shapes",        topic: "shapes",   stars: 1, status: "current" },
      { n: 5, title_fr: "Les soustractions", title_en: "Take away",     topic: "sub",      stars: 0, status: "locked" },
      { n: 6, title_fr: "Les suites",        title_en: "Patterns",      topic: "patterns", stars: 0, status: "locked" },
      { n: 7, title_fr: "L'heure",           title_en: "Telling time",  topic: "time",     stars: 0, status: "locked" },
      { n: 8, title_fr: "Le grand défi",     title_en: "Big challenge", topic: "boss",     stars: 0, status: "locked", boss: true },
    ],
  },

  // Sample questions by topic (3 per topic, used for quiz preview)
  questions: {
    family: [
      { q_fr: "Comment dit-on 'maman' en anglais ?", q_en: "How do you say 'maman' in English?",
        opts: [ {fr:"Mother",en:"Mother",emoji:"👩"}, {fr:"Father",en:"Father",emoji:"👨"}, {fr:"Sister",en:"Sister",emoji:"👧"} ],
        correct: 0 },
      { q_fr: "Quel mot pour 'papa' ?", q_en: "Which word means 'papa'?",
        opts: [ {fr:"Brother",en:"Brother",emoji:"👦"}, {fr:"Father",en:"Father",emoji:"👨"}, {fr:"Baby",en:"Baby",emoji:"👶"} ],
        correct: 1 },
      { q_fr: "Et 'bébé' ?", q_en: "And 'bébé'?",
        opts: [ {fr:"Baby",en:"Baby",emoji:"👶"}, {fr:"Dog",en:"Dog",emoji:"🐶"}, {fr:"Cat",en:"Cat",emoji:"🐱"} ],
        correct: 0 },
    ],
    flags: [
      { q_fr: "Quel est le drapeau de la France ?", q_en: "Which flag is France?",
        opts: [ {fr:"🇫🇷",en:"🇫🇷",emoji:"🇫🇷"}, {fr:"🇮🇹",en:"🇮🇹",emoji:"🇮🇹"}, {fr:"🇪🇸",en:"🇪🇸",emoji:"🇪🇸"} ],
        correct: 0 },
      { q_fr: "Lequel est le drapeau du Japon ?", q_en: "Which one is Japan's flag?",
        opts: [ {fr:"🇨🇳",en:"🇨🇳",emoji:"🇨🇳"}, {fr:"🇯🇵",en:"🇯🇵",emoji:"🇯🇵"}, {fr:"🇰🇷",en:"🇰🇷",emoji:"🇰🇷"} ],
        correct: 1 },
      { q_fr: "Et le Brésil ?", q_en: "And Brazil?",
        opts: [ {fr:"🇦🇷",en:"🇦🇷",emoji:"🇦🇷"}, {fr:"🇲🇽",en:"🇲🇽",emoji:"🇲🇽"}, {fr:"🇧🇷",en:"🇧🇷",emoji:"🇧🇷"} ],
        correct: 2 },
    ],
    shapes: [
      { q_fr: "Quelle est la forme du soleil ?", q_en: "What shape is the sun?",
        opts: [ {fr:"Cercle",en:"Circle",emoji:"⭕"}, {fr:"Carré",en:"Square",emoji:"⬜"}, {fr:"Triangle",en:"Triangle",emoji:"🔺"} ],
        correct: 0 },
      { q_fr: "Trouve le triangle.", q_en: "Find the triangle.",
        opts: [ {fr:"Étoile",en:"Star",emoji:"⭐"}, {fr:"Triangle",en:"Triangle",emoji:"🔺"}, {fr:"Cœur",en:"Heart",emoji:"❤️"} ],
        correct: 1 },
      { q_fr: "Combien de côtés a un carré ?", q_en: "How many sides has a square?",
        opts: [ {fr:"3",en:"3",emoji:"3️⃣"}, {fr:"4",en:"4",emoji:"4️⃣"}, {fr:"5",en:"5",emoji:"5️⃣"} ],
        correct: 1 },
    ],
  },

  trophies: [
    { id: "first_step",   emoji: "👶", title_fr: "Premier pas",      title_en: "First step",        owned: true,
      desc_fr: "Tu as fini ta première leçon !", desc_en: "You finished your first lesson!" },
    { id: "english_star", emoji: "📚", title_fr: "Étoile d'anglais", title_en: "English star",      owned: true,
      desc_fr: "3 leçons d'anglais finies",     desc_en: "3 English lessons done" },
    { id: "globe_trotter",emoji: "🌍", title_fr: "Tour du monde",    title_en: "Globe trotter",     owned: true,
      desc_fr: "Tu as visité 2 continents",     desc_en: "Visited 2 continents" },
    { id: "math_genius",  emoji: "🧮", title_fr: "Génie des chiffres",title_en: "Math genius",      owned: true,
      desc_fr: "10 additions correctes d'affilée", desc_en: "10 correct additions in a row" },
    { id: "streak_7",     emoji: "🔥", title_fr: "Série de 7",       title_en: "7-day streak",      owned: true,
      desc_fr: "Tu as joué 7 jours d'affilée",  desc_en: "You played 7 days in a row" },
    { id: "perfect",      emoji: "💎", title_fr: "Score parfait",    title_en: "Perfect score",     owned: false,
      desc_fr: "Termine une leçon sans erreur", desc_en: "Finish a lesson with no mistake" },
    { id: "explorer",     emoji: "🗺️", title_fr: "Grand explorateur", title_en: "Great explorer",   owned: false,
      desc_fr: "Visite tous les continents",    desc_en: "Visit every continent" },
    { id: "speedster",    emoji: "⚡", title_fr: "Éclair",           title_en: "Speedster",         owned: false,
      desc_fr: "Termine une leçon en 1 min",    desc_en: "Finish a lesson in 1 min" },
    { id: "wordsmith",    emoji: "🪄", title_fr: "Magicien des mots",title_en: "Wordsmith",        owned: false,
      desc_fr: "Apprends 50 mots d'anglais",    desc_en: "Learn 50 English words" },
    { id: "all_stars",    emoji: "🏆", title_fr: "Tout en étoiles",  title_en: "All stars",         owned: false,
      desc_fr: "Gagne 3 étoiles sur tous les niveaux", desc_en: "Earn 3 stars on every level" },
  ],
};
