// data.js — i18n strings, sport meta, match data
// Globals attached to window for use across script files.

window.I18N = {
  fr: {
    // Nav
    dashboard: "Tableau de bord",
    matches: "Matchs",
    analysis: "Analyses",
    tactics: "Tactiques",
    compare: "Comparateur",
    simulator: "Simulateur",
    trends: "Tendances",
    history: "Historique",
    settings: "Paramètres",
    // Sports
    football: "Football",
    basket: "Basket",
    rugby: "Rugby",
    // Header
    search: "Rechercher une équipe, un match…",
    new_analysis: "Nouvelle analyse",
    // Dashboard
    welcome: "Bonjour, Coach",
    dashboard_sub: "Voici l'activité tactique de la semaine.",
    upcoming: "À venir",
    upcoming_sub: "Matchs à analyser avant le coup d'envoi",
    recent: "Récents",
    recent_sub: "Analyses post-match disponibles",
    quick_stats: "Indicateurs",
    matches_analyzed: "Matchs analysés",
    avg_accuracy: "Précision moyenne",
    competitions: "Compétitions",
    saved_reports: "Rapports sauvegardés",
    this_month: "ce mois",
    vs_last: "vs précédent",
    pre_match: "Pré-match",
    post_match: "Post-match",
    live: "Direct",
    finished: "Terminé",
    upcoming_pill: "À venir",
    analyze: "Analyser",
    review: "Revoir",
    view: "Voir",
    in_progress: "En cours",
    // Match list
    all_competitions: "Toutes les compétitions",
    today: "Aujourd'hui",
    this_week: "Cette semaine",
    filter: "Filtrer",
    // Pre-match
    formation: "Composition probable",
    key_matchups: "Duels clés",
    tactical_brief: "Briefing tactique",
    expected_lineups: "Onze attendu",
    coach_view: "Vue du coach",
    predicted_score: "Score prédit",
    win_probability: "Probabilité de victoire",
    draw: "Nul",
    home_strengths: "Points forts (domicile)",
    away_strengths: "Points forts (extérieur)",
    watch_for: "À surveiller",
    generate: "Générer l'analyse",
    // Post-match
    full_time: "Temps réglementaire",
    verdict: "Verdict du coach",
    key_stats: "Statistiques clés",
    possession: "Possession",
    shots: "Tirs",
    shots_on_target: "Cadrés",
    xg: "xG",
    passes: "Passes",
    pass_accuracy: "Précision passes",
    fouls: "Fautes",
    corners: "Corners",
    top_performers: "Joueurs en vue",
    rating: "Note",
    timeline: "Chronologie",
    export_pdf: "Exporter PDF",
    share: "Partager",
    // Settings
    language: "Langue",
    api_key: "Clé API Claude",
    api_key_set: "Clé API configurée",
    api_key_missing: "Clé API requise",
    appearance: "Apparence",
    preferred_sport: "Sport favori",
    notifications: "Notifications",
    notif_pre: "Rappel pré-match (2h avant)",
    notif_post: "Analyse disponible",
    save: "Enregistrer",
    // Misc
    footer: "Propulsé par Claude AI · Anthropic",
    no_data: "Aucun match pour cette sélection.",
    loading: "Analyse en cours…",
  },
  en: {
    dashboard: "Dashboard",
    matches: "Matches",
    analysis: "Analysis",
    tactics: "Tactics",
    compare: "Comparator",
    simulator: "Simulator",
    trends: "Trends",
    history: "History",
    settings: "Settings",
    football: "Football",
    basket: "Basketball",
    rugby: "Rugby",
    search: "Search a team, a match…",
    new_analysis: "New analysis",
    welcome: "Hello, Coach",
    dashboard_sub: "Here's this week's tactical activity.",
    upcoming: "Upcoming",
    upcoming_sub: "Matches to analyze before kick-off",
    recent: "Recent",
    recent_sub: "Post-match analyses available",
    quick_stats: "Key indicators",
    matches_analyzed: "Matches analyzed",
    avg_accuracy: "Average accuracy",
    competitions: "Competitions",
    saved_reports: "Saved reports",
    this_month: "this month",
    vs_last: "vs last",
    pre_match: "Pre-match",
    post_match: "Post-match",
    live: "Live",
    finished: "Finished",
    upcoming_pill: "Upcoming",
    analyze: "Analyze",
    review: "Review",
    view: "View",
    in_progress: "In progress",
    all_competitions: "All competitions",
    today: "Today",
    this_week: "This week",
    filter: "Filter",
    formation: "Probable lineup",
    key_matchups: "Key matchups",
    tactical_brief: "Tactical brief",
    expected_lineups: "Expected starting XI",
    coach_view: "Coach's view",
    predicted_score: "Predicted score",
    win_probability: "Win probability",
    draw: "Draw",
    home_strengths: "Home strengths",
    away_strengths: "Away strengths",
    watch_for: "Watch for",
    generate: "Generate analysis",
    full_time: "Full time",
    verdict: "Coach's verdict",
    key_stats: "Key stats",
    possession: "Possession",
    shots: "Shots",
    shots_on_target: "On target",
    xg: "xG",
    passes: "Passes",
    pass_accuracy: "Pass accuracy",
    fouls: "Fouls",
    corners: "Corners",
    top_performers: "Top performers",
    rating: "Rating",
    timeline: "Timeline",
    export_pdf: "Export PDF",
    share: "Share",
    language: "Language",
    api_key: "Claude API key",
    api_key_set: "API key configured",
    api_key_missing: "API key required",
    appearance: "Appearance",
    preferred_sport: "Favourite sport",
    notifications: "Notifications",
    notif_pre: "Pre-match reminder (2h before)",
    notif_post: "Analysis available",
    save: "Save",
    footer: "Powered by Claude AI · Anthropic",
    no_data: "No match for this selection.",
    loading: "Analysis in progress…",
  },
};

window.SPORTS = [
  { id: "football", emoji: "⚽", label_fr: "Football", label_en: "Football" },
  { id: "basket",   emoji: "🏀", label_fr: "Basket",   label_en: "Basketball" },
  { id: "rugby",    emoji: "🏉", label_fr: "Rugby",    label_en: "Rugby" },
];

// (window.MATCHES & window.LINEUPS are injected with real data by coachiq_app.py)

window.COMPETITIONS = [
  { id: "all",  fr: "Toutes",          en: "All",            sports: ["football","basket","rugby"] },
  { id: "l1",   fr: "Ligue 1",         en: "Ligue 1",        sports: ["football"] },
  { id: "pl",   fr: "Premier League",  en: "Premier League", sports: ["football"] },
  { id: "ll",   fr: "LaLiga",          en: "LaLiga",         sports: ["football"] },
  { id: "ucl",  fr: "Champions L.",    en: "Champions L.",   sports: ["football"] },
  { id: "bun",  fr: "Bundesliga",      en: "Bundesliga",     sports: ["football"] },
  { id: "nba",  fr: "NBA",             en: "NBA",            sports: ["basket"] },
  { id: "eur",  fr: "Euroleague",      en: "Euroleague",     sports: ["basket"] },
  { id: "t14",  fr: "Top 14",          en: "Top 14",         sports: ["rugby"] },
  { id: "tst",  fr: "Test Match",      en: "Test Match",     sports: ["rugby"] },
];
