// data.js — i18n strings, sport meta, match data
// Globals attached to window for use across script files.

window.I18N = {
  fr: {
    // Nav
    dashboard: "Tableau de bord",
    matches: "Matchs",
    analysis: "Analyses",
    history: "Historique",
    settings: "Paramètres",
    // Sports
    football: "Football",
    basket: "Basket",
    rugby: "Rugby",
    // Header
    search: "Rechercher une équipe, un match…",
    new_analysis: "Nouvelle analyse",
    // Dashboard
    welcome: "Bonjour, Coach",
    dashboard_sub: "Voici l'activité tactique de la semaine.",
    upcoming: "À venir",
    upcoming_sub: "Matchs à analyser avant le coup d'envoi",
    recent: "Récents",
    recent_sub: "Analyses post-match disponibles",
    quick_stats: "Indicateurs",
    matches_analyzed: "Matchs analysés",
    avg_accuracy: "Précision moyenne",
    competitions: "Compétitions",
    saved_reports: "Rapports sauvegardés",
    this_month: "ce mois",
    vs_last: "vs précédent",
    pre_match: "Pré-match",
    post_match: "Post-match",
    live: "Direct",
    finished: "Terminé",
    upcoming_pill: "À venir",
    analyze: "Analyser",
    review: "Revoir",
    view: "Voir",
    in_progress: "En cours",
    // Match list
    all_competitions: "Toutes les compétitions",
    today: "Aujourd'hui",
    this_week: "Cette semaine",
    filter: "Filtrer",
    // Pre-match
    formation: "Composition probable",
    key_matchups: "Duels clés",
    tactical_brief: "Briefing tactique",
    expected_lineups: "Onze attendu",
    coach_view: "Vue du coach",
    predicted_score: "Score prédit",
    win_probability: "Probabilité de victoire",
    draw: "Nul",
    home_strengths: "Points forts (domicile)",
    away_strengths: "Points forts (extérieur)",
    watch_for: "À surveiller",
    generate: "Générer l'analyse",
    // Post-match
    full_time: "Temps réglementaire",
    verdict: "Verdict du coach",
    key_stats: "Statistiques clés",
    possession: "Possession",
    shots: "Tirs",
    shots_on_target: "Cadrés",
    xg: "xG",
    passes: "Passes",
    pass_accuracy: "Précision passes",
    fouls: "Fautes",
    corners: "Corners",
    top_performers: "Joueurs en vue",
    rating: "Note",
    timeline: "Chronologie",
    export_pdf: "Exporter PDF",
    share: "Partager",
    // Settings
    language: "Langue",
    api_key: "Clé API Claude",
    api_key_set: "Clé API configurée",
    api_key_missing: "Clé API requise",
    appearance: "Apparence",
    preferred_sport: "Sport favori",
    notifications: "Notifications",
    notif_pre: "Rappel pré-match (2h avant)",
    notif_post: "Analyse disponible",
    save: "Enregistrer",
    // Misc
    footer: "Propulsé par Claude AI · Anthropic",
    no_data: "Aucun match pour cette sélection.",
    loading: "Analyse en cours…",
  },
  en: {
    dashboard: "Dashboard",
    matches: "Matches",
    analysis: "Analysis",
    history: "History",
    settings: "Settings",
    football: "Football",
    basket: "Basketball",
    rugby: "Rugby",
    search: "Search a team, a match…",
    new_analysis: "New analysis",
    welcome: "Hello, Coach",
    dashboard_sub: "Here's this week's tactical activity.",
    upcoming: "Upcoming",
    upcoming_sub: "Matches to analyze before kick-off",
    recent: "Recent",
    recent_sub: "Post-match analyses available",
    quick_stats: "Key indicators",
    matches_analyzed: "Matches analyzed",
    avg_accuracy: "Average accuracy",
    competitions: "Competitions",
    saved_reports: "Saved reports",
    this_month: "this month",
    vs_last: "vs last",
    pre_match: "Pre-match",
    post_match: "Post-match",
    live: "Live",
    finished: "Finished",
    upcoming_pill: "Upcoming",
    analyze: "Analyze",
    review: "Review",
    view: "View",
    in_progress: "In progress",
    all_competitions: "All competitions",
    today: "Today",
    this_week: "This week",
    filter: "Filter",
    formation: "Probable lineup",
    key_matchups: "Key matchups",
    tactical_brief: "Tactical brief",
    expected_lineups: "Expected starting XI",
    coach_view: "Coach's view",
    predicted_score: "Predicted score",
    win_probability: "Win probability",
    draw: "Draw",
    home_strengths: "Home strengths",
    away_strengths: "Away strengths",
    watch_for: "Watch for",
    generate: "Generate analysis",
    full_time: "Full time",
    verdict: "Coach's verdict",
    key_stats: "Key stats",
    possession: "Possession",
    shots: "Shots",
    shots_on_target: "On target",
    xg: "xG",
    passes: "Passes",
    pass_accuracy: "Pass accuracy",
    fouls: "Fouls",
    corners: "Corners",
    top_performers: "Top performers",
    rating: "Rating",
    timeline: "Timeline",
    export_pdf: "Export PDF",
    share: "Share",
    language: "Language",
    api_key: "Claude API key",
    api_key_set: "API key configured",
    api_key_missing: "API key required",
    appearance: "Appearance",
    preferred_sport: "Favourite sport",
    notifications: "Notifications",
    notif_pre: "Pre-match reminder (2h before)",
    notif_post: "Analysis available",
    save: "Save",
    footer: "Powered by Claude AI · Anthropic",
    no_data: "No match for this selection.",
    loading: "Analysis in progress…",
  },
};

window.SPORTS = [
  { id: "football", emoji: "⚽", label_fr: "Football", label_en: "Football" },
  { id: "basket",   emoji: "🏀", label_fr: "Basket",   label_en: "Basketball" },
  { id: "rugby",    emoji: "🏉", label_fr: "Rugby",    label_en: "Rugby" },
];

// Realistic, generic-leaning match data. Two-letter team codes used in cards.
window.MATCHES = {
  football: [
    {
      id: "psg-om", status: "upcoming", date: "Dim. 02 Juin · 21:00",
      competition: "Ligue 1 · J35", venue: "Parc des Princes",
      home: { code: "PSG", name: "Paris SG", color: "#004170", form: ["V","V","N","V","V"], rank: 1 },
      away: { code: "OM",  name: "Marseille", color: "#2FAEE0", form: ["V","D","V","N","V"], rank: 4 },
      odds: { home: 1.42, draw: 4.80, away: 6.50 }, predicted: "2 – 1",
    },
    {
      id: "rma-fcb", status: "upcoming", date: "Sam. 01 Juin · 21:00",
      competition: "LaLiga · J36", venue: "Santiago Bernabéu",
      home: { code: "RMA", name: "Real Madrid", color: "#febe10", form: ["V","V","V","N","V"], rank: 1 },
      away: { code: "FCB", name: "Barcelona", color: "#a50044", form: ["V","V","V","V","D"], rank: 2 },
      odds: { home: 2.10, draw: 3.60, away: 3.20 }, predicted: "2 – 2",
    },
    {
      id: "mci-ars", status: "live", date: "En direct · 67'",
      competition: "Premier League · J37", venue: "Etihad Stadium",
      score: { home: 1, away: 1 },
      home: { code: "MCI", name: "Man City", color: "#6CABDD", form: ["V","V","V","V","N"], rank: 1 },
      away: { code: "ARS", name: "Arsenal", color: "#EF0107", form: ["V","V","N","V","V"], rank: 2 },
    },
    {
      id: "liv-tot", status: "finished", date: "Dim. 26 Mai",
      competition: "Premier League · J38", venue: "Anfield",
      score: { home: 3, away: 1 },
      home: { code: "LIV", name: "Liverpool", color: "#C8102E", form: ["V","V","V","D","V"], rank: 3 },
      away: { code: "TOT", name: "Tottenham", color: "#132257", form: ["D","V","D","N","D"], rank: 5 },
      verdict_fr: "Liverpool a écrasé le bloc bas de Tottenham par la verticalité d'Alexander-Arnold. Le pressing 4-2-4 a étouffé toute relance.",
      verdict_en: "Liverpool overwhelmed Tottenham's low block through Alexander-Arnold's verticality. The 4-2-4 press suffocated all build-up.",
    },
    {
      id: "bay-bvb", status: "finished", date: "Sam. 25 Mai",
      competition: "Bundesliga · J34", venue: "Allianz Arena",
      score: { home: 2, away: 2 },
      home: { code: "BAY", name: "Bayern", color: "#DC052D", form: ["V","N","V","D","N"], rank: 3 },
      away: { code: "BVB", name: "Dortmund", color: "#FDE100", form: ["V","V","N","D","N"], rank: 5 },
      verdict_fr: "Match d'égos sur l'aile gauche. Le 4-2-3-1 de Tuchel a manqué de profondeur après la sortie de Musiala.",
      verdict_en: "Battle of egos on the left flank. Tuchel's 4-2-3-1 lacked depth after Musiala's substitution.",
    },
  ],
  basket: [
    {
      id: "lal-bos", status: "upcoming", date: "Mar. 04 Juin · 02:30",
      competition: "NBA Finals · Game 1", venue: "TD Garden",
      home: { code: "BOS", name: "Celtics", color: "#007A33", form: ["V","V","V","V","V"], rank: 1 },
      away: { code: "LAL", name: "Lakers", color: "#552583", form: ["V","V","D","V","V"], rank: 6 },
      odds: { home: 1.55, draw: null, away: 2.40 }, predicted: "112 – 104",
    },
    {
      id: "den-mil", status: "finished", date: "Mar. 28 Mai",
      competition: "NBA · Saison régulière", venue: "Ball Arena",
      score: { home: 118, away: 109 },
      home: { code: "DEN", name: "Nuggets", color: "#0E2240", form: ["V","V","D","V","V"], rank: 2 },
      away: { code: "MIL", name: "Bucks", color: "#00471B", form: ["V","D","V","D","V"], rank: 3 },
      verdict_fr: "Jokic a déchiré la défense en switch des Bucks. 14 passes décisives, 70% au tir.",
      verdict_en: "Jokic dismantled the Bucks' switching defense. 14 assists, 70% shooting.",
    },
  ],
  rugby: [
    {
      id: "tls-rch", status: "upcoming", date: "Sam. 08 Juin · 21:05",
      competition: "Top 14 · Finale", venue: "Stade de France",
      home: { code: "TLS", name: "Stade Toulousain", color: "#a40e26", form: ["V","V","V","V","V"], rank: 1 },
      away: { code: "RCH", name: "La Rochelle", color: "#FFD700", form: ["V","D","V","V","V"], rank: 3 },
      odds: { home: 1.65, draw: 20.0, away: 2.20 }, predicted: "28 – 22",
    },
    {
      id: "fra-nzl", status: "finished", date: "Sam. 25 Mai",
      competition: "Test Match", venue: "Stade de France",
      score: { home: 31, away: 28 },
      home: { code: "FRA", name: "XV de France", color: "#1f3a93", form: ["V","V","N","V","D"], rank: 2 },
      away: { code: "NZL", name: "All Blacks", color: "#000000", form: ["V","V","V","D","V"], rank: 1 },
      verdict_fr: "Les Bleus ont gagné la bataille des rucks (94% de conservation) et coupé la transmission néo-zélandaise.",
      verdict_en: "Les Bleus won the ruck battle (94% retention) and severed the All Blacks' transmission.",
    },
  ],
};

// Sample lineup data for pre-match formations (football)
window.LINEUPS = {
  "psg-om": {
    home: {
      formation: "4-3-3",
      players: [
        { pos: "GK", x: 50, y: 92, num: 1,  name: "Donnarumma" },
        { pos: "DEF", x: 12, y: 72, num: 25, name: "Mendes" },
        { pos: "DEF", x: 36, y: 76, num: 4,  name: "Skriniar" },
        { pos: "DEF", x: 64, y: 76, num: 5,  name: "Marquinhos" },
        { pos: "DEF", x: 88, y: 72, num: 2,  name: "Hakimi" },
        { pos: "MID", x: 25, y: 50, num: 8,  name: "Vitinha" },
        { pos: "MID", x: 50, y: 56, num: 17, name: "Zaïre-Emery" },
        { pos: "MID", x: 75, y: 50, num: 87, name: "Ruiz" },
        { pos: "FWD", x: 18, y: 24, num: 10, name: "Dembélé" },
        { pos: "FWD", x: 50, y: 18, num: 9,  name: "Ramos" },
        { pos: "FWD", x: 82, y: 24, num: 7,  name: "Barcola" },
      ],
    },
    away: {
      formation: "3-4-2-1",
      players: [
        { pos: "GK", x: 50, y: 92, num: 30, name: "Lopez" },
        { pos: "DEF", x: 22, y: 76, num: 6,  name: "Gigot" },
        { pos: "DEF", x: 50, y: 80, num: 5,  name: "Balerdi" },
        { pos: "DEF", x: 78, y: 76, num: 14, name: "Mbemba" },
        { pos: "MID", x: 10, y: 52, num: 12, name: "Clauss" },
        { pos: "MID", x: 38, y: 56, num: 22, name: "Veretout" },
        { pos: "MID", x: 62, y: 56, num: 8,  name: "Kondogbia" },
        { pos: "MID", x: 90, y: 52, num: 3,  name: "Lodi" },
        { pos: "FWD", x: 32, y: 28, num: 17, name: "Sarr" },
        { pos: "FWD", x: 68, y: 28, num: 7,  name: "Harit" },
        { pos: "FWD", x: 50, y: 14, num: 9,  name: "Aubameyang" },
      ],
    },
  },
};

window.COMPETITIONS = [
  { id: "all",  fr: "Toutes",          en: "All",            sports: ["football","basket","rugby"] },
  { id: "l1",   fr: "Ligue 1",         en: "Ligue 1",        sports: ["football"] },
  { id: "pl",   fr: "Premier League",  en: "Premier League", sports: ["football"] },
  { id: "ll",   fr: "LaLiga",          en: "LaLiga",         sports: ["football"] },
  { id: "ucl",  fr: "Champions L.",    en: "Champions L.",   sports: ["football"] },
  { id: "bun",  fr: "Bundesliga",      en: "Bundesliga",     sports: ["football"] },
  { id: "nba",  fr: "NBA",             en: "NBA",            sports: ["basket"] },
  { id: "eur",  fr: "Euroleague",      en: "Euroleague",     sports: ["basket"] },
  { id: "t14",  fr: "Top 14",          en: "Top 14",         sports: ["rugby"] },
  { id: "tst",  fr: "Test Match",      en: "Test Match",     sports: ["rugby"] },
];
