// data.js — AuditIQ i18n, jurisdictions, sample audits, agents

window.AIQ = {
  i18n: {
    fr: {
      brand: "AuditIQ",
      tagline: "Audit bancaire augmenté par l'IA",
      intro_sub: "Cadre réglementaire · Plan d'audit · Rapport",
      enter: "Entrer",
      // Nav
      dashboard: "Tableau de bord",
      audits: "Audits",
      regulatory: "Cadre réglementaire",
      audit_plan: "Plan d'audit",
      audit_report: "Rapport d'audit",
      documents: "Documents",
      history: "Historique",
      settings: "Paramètres",
      agents_label: "Agents IA",
      tools_label: "Outils",
      account_label: "Compte",
      // Dashboard
      welcome: "Bienvenue, Lucas",
      welcome_sub: "Voici l'état de vos audits en cours.",
      new_audit: "Nouvel audit",
      kpi_audits: "Audits actifs",
      kpi_completed: "Audits clôturés",
      kpi_pending: "Recommandations en attente",
      kpi_jurisdictions: "Juridictions couvertes",
      this_month: "ce mois",
      vs_last_q: "vs trimestre précédent",
      recent_activity: "Activité récente",
      next_milestones: "Prochaines échéances",
      due_in_days: "dans {n} jours",
      view_all: "Tout voir",
      agent_status: "État des agents",
      // Generic
      search: "Rechercher un audit, une réglementation...",
      generate: "Lancer l'analyse",
      generating: "Génération en cours…",
      done: "Terminé",
      in_progress: "En cours",
      draft: "Brouillon",
      review: "À revoir",
      approved: "Approuvé",
      severity: "Sévérité",
      critical: "Critique",
      high: "Élevé",
      medium: "Moyen",
      low: "Faible",
      info: "Info",
      // Forms
      audit_subject: "Sujet d'audit",
      audit_subject_ph: "Ex : Lutte contre le blanchiment de capitaux",
      audit_scope: "Périmètre de l'audit",
      audit_scope_ph: "Ex : Activités de banque privée en Suisse et à Singapour",
      audit_scope_opt: "Périmètre (optionnel)",
      jurisdiction: "Juridiction(s)",
      regulation: "Réglementation",
      framework: "Cadre",
      period: "Période",
      // Agent 1
      agent1_title: "Agent 1 — Cadre réglementaire",
      agent1_desc: "Compile les lois, réglementations et guidelines applicables sur 6 juridictions pour un sujet d'audit donné.",
      generate_framework: "Générer le cadre",
      framework_ready: "Cadre réglementaire disponible",
      framework_missing: "Cadre réglementaire requis",
      // Agent 2
      agent2_title: "Agent 2 — Plan d'audit",
      agent2_desc: "Décline le cadre en un plan d'audit structuré : étapes, contrôles, procédures, échantillonnage.",
      generate_plan: "Générer le plan",
      plan_ready: "Plan d'audit disponible",
      plan_missing: "Plan d'audit requis",
      // Agent 3
      agent3_title: "Agent 3 — Rapport d'audit",
      agent3_desc: "Produit un rapport exécutif synthétique : constats, gravité, recommandations, plan d'action.",
      generate_report: "Générer le rapport",
      report_ready: "Rapport d'audit disponible",
      report_missing: "Rapport d'audit requis",
      // Output
      output: "Sortie",
      preview: "Aperçu",
      download_word: "Télécharger Word",
      download_pptx: "Télécharger PowerPoint",
      download_xlsx: "Télécharger Excel",
      download_pdf: "Télécharger PDF",
      // Documents
      docs_sub: "Tous les livrables générés par AuditIQ",
      doc_type: "Type",
      doc_audit: "Audit",
      doc_date: "Date",
      doc_size: "Taille",
      doc_status: "Statut",
      // Settings
      api_key: "Clé API Claude",
      api_key_ph: "sk-ant-...",
      api_key_set: "Clé API configurée",
      api_key_missing: "Clé API requise",
      language: "Langue d'interface",
      model: "Modèle Claude",
      thinking: "Mode raisonnement",
      thinking_desc: "Active le raisonnement étendu (plus lent, plus précis)",
      org: "Organisation",
      // Status
      status_label: "Statut",
      status_active: "Actif",
      status_review: "À revoir",
      status_closed: "Clôturé",
      // Misc
      footer: "Propulsé par Claude AI · Anthropic",
      no_data: "Aucune donnée à afficher.",
      hint_required: "Champs requis",
      ago: "il y a",
      minutes: "min",
      hours: "h",
      days: "j",
      // Severity descriptions
      sev_critical_d: "Impact réglementaire immédiat",
      sev_high_d: "Action sous 30 jours",
      sev_medium_d: "À traiter au prochain cycle",
      sev_low_d: "Veille à maintenir",
    },
    en: {
      brand: "AuditIQ",
      tagline: "AI-augmented banking audit",
      intro_sub: "Regulatory framework · Audit plan · Report",
      enter: "Enter",
      dashboard: "Dashboard",
      audits: "Audits",
      regulatory: "Regulatory framework",
      audit_plan: "Audit plan",
      audit_report: "Audit report",
      documents: "Documents",
      history: "History",
      settings: "Settings",
      agents_label: "AI Agents",
      tools_label: "Tools",
      account_label: "Account",
      welcome: "Welcome, Lucas",
      welcome_sub: "Here's the status of your ongoing audits.",
      new_audit: "New audit",
      kpi_audits: "Active audits",
      kpi_completed: "Completed audits",
      kpi_pending: "Pending recommendations",
      kpi_jurisdictions: "Jurisdictions covered",
      this_month: "this month",
      vs_last_q: "vs last quarter",
      recent_activity: "Recent activity",
      next_milestones: "Upcoming milestones",
      due_in_days: "in {n} days",
      view_all: "View all",
      agent_status: "Agent status",
      search: "Search an audit, a regulation...",
      generate: "Run analysis",
      generating: "Generating…",
      done: "Done",
      in_progress: "In progress",
      draft: "Draft",
      review: "To review",
      approved: "Approved",
      severity: "Severity",
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
      info: "Info",
      audit_subject: "Audit subject",
      audit_subject_ph: "E.g. Anti-money-laundering",
      audit_scope: "Audit scope",
      audit_scope_ph: "E.g. Private banking in Switzerland and Singapore",
      audit_scope_opt: "Scope (optional)",
      jurisdiction: "Jurisdiction(s)",
      regulation: "Regulation",
      framework: "Framework",
      period: "Period",
      agent1_title: "Agent 1 — Regulatory framework",
      agent1_desc: "Compiles applicable laws, regulations and guidelines across 6 jurisdictions for a given audit subject.",
      generate_framework: "Generate framework",
      framework_ready: "Regulatory framework available",
      framework_missing: "Regulatory framework required",
      agent2_title: "Agent 2 — Audit plan",
      agent2_desc: "Turns the framework into a structured audit plan: steps, controls, procedures, sampling.",
      generate_plan: "Generate plan",
      plan_ready: "Audit plan available",
      plan_missing: "Audit plan required",
      agent3_title: "Agent 3 — Audit report",
      agent3_desc: "Produces an executive synthesis: findings, severity, recommendations, action plan.",
      generate_report: "Generate report",
      report_ready: "Audit report available",
      report_missing: "Audit report required",
      output: "Output",
      preview: "Preview",
      download_word: "Download Word",
      download_pptx: "Download PowerPoint",
      download_xlsx: "Download Excel",
      download_pdf: "Download PDF",
      docs_sub: "All deliverables generated by AuditIQ",
      doc_type: "Type",
      doc_audit: "Audit",
      doc_date: "Date",
      doc_size: "Size",
      doc_status: "Status",
      api_key: "Claude API key",
      api_key_ph: "sk-ant-...",
      api_key_set: "API key configured",
      api_key_missing: "API key required",
      language: "Interface language",
      model: "Claude model",
      thinking: "Reasoning mode",
      thinking_desc: "Enable extended reasoning (slower, more accurate)",
      org: "Organization",
      status_label: "Status",
      status_active: "Active",
      status_review: "To review",
      status_closed: "Closed",
      footer: "Powered by Claude AI · Anthropic",
      no_data: "No data to display.",
      hint_required: "Required fields",
      ago: "",
      minutes: "min ago",
      hours: "h ago",
      days: "d ago",
      sev_critical_d: "Immediate regulatory impact",
      sev_high_d: "Action within 30 days",
      sev_medium_d: "Address in next cycle",
      sev_low_d: "Keep monitoring",
    },
  },

  jurisdictions: [
    { id: "ch", fr: "Suisse", en: "Switzerland", flag: "🇨🇭", regulator: "FINMA" },
    { id: "sg", fr: "Singapour", en: "Singapore", flag: "🇸🇬", regulator: "MAS" },
    { id: "hk", fr: "Hong Kong", en: "Hong Kong", flag: "🇭🇰", regulator: "HKMA · SFC" },
    { id: "bs", fr: "Bahamas", en: "Bahamas", flag: "🇧🇸", regulator: "CBB · SCB" },
    { id: "eu", fr: "Union Européenne", en: "European Union", flag: "🇪🇺", regulator: "EBA · ECB" },
    { id: "uk", fr: "Royaume-Uni", en: "United Kingdom", flag: "🇬🇧", regulator: "FCA · PRA" },
  ],

  topics: [
    { id: "aml",  fr: "Lutte contre le blanchiment (AML)", en: "Anti-money-laundering (AML)" },
    { id: "kyc",  fr: "Connaissance du client (KYC)",       en: "Know-your-customer (KYC)" },
    { id: "mar",  fr: "Abus de marché (MAR)",               en: "Market abuse (MAR)" },
    { id: "icaap",fr: "Adéquation des fonds propres",       en: "Capital adequacy (ICAAP)" },
    { id: "ops",  fr: "Risque opérationnel",                en: "Operational risk" },
    { id: "cyber",fr: "Cybersécurité",                      en: "Cybersecurity" },
    { id: "esg",  fr: "Risques ESG & climat",               en: "ESG & climate risk" },
    { id: "dora", fr: "DORA — Résilience opérationnelle",   en: "DORA — Operational resilience" },
  ],

  // Live audits
  audits: [
    {
      id: "AUD-2026-014",
      subject_fr: "Lutte contre le blanchiment — Banque privée CH/SG",
      subject_en: "AML — Private banking CH/SG",
      jurisdictions: ["ch", "sg"],
      regulators: ["FINMA", "MAS"],
      status: "active",
      progress: 68,
      owner: "L. Brunner",
      due: "12 juin 2026",
      due_in: 15,
      severity: "high",
      stage: "agent2",
    },
    {
      id: "AUD-2026-013",
      subject_fr: "Résilience opérationnelle (DORA) — Périmètre UE",
      subject_en: "Operational resilience (DORA) — EU scope",
      jurisdictions: ["eu"],
      regulators: ["EBA"],
      status: "review",
      progress: 92,
      owner: "M. Tanaka",
      due: "30 mai 2026",
      due_in: 2,
      severity: "critical",
      stage: "agent3",
    },
    {
      id: "AUD-2026-012",
      subject_fr: "KYC client de haute valeur — Hong Kong",
      subject_en: "High-net-worth KYC — Hong Kong",
      jurisdictions: ["hk"],
      regulators: ["HKMA", "SFC"],
      status: "active",
      progress: 42,
      owner: "A. Cheung",
      due: "28 juin 2026",
      due_in: 31,
      severity: "medium",
      stage: "agent1",
    },
    {
      id: "AUD-2026-011",
      subject_fr: "Risque opérationnel — Bahamas",
      subject_en: "Operational risk — Bahamas",
      jurisdictions: ["bs"],
      regulators: ["CBB"],
      status: "active",
      progress: 25,
      owner: "R. Patel",
      due: "22 juillet 2026",
      due_in: 55,
      severity: "medium",
      stage: "agent1",
    },
    {
      id: "AUD-2026-010",
      subject_fr: "Cybersécurité & continuité — UK",
      subject_en: "Cybersecurity & continuity — UK",
      jurisdictions: ["uk"],
      regulators: ["FCA", "PRA"],
      status: "closed",
      progress: 100,
      owner: "S. Holm",
      due: "15 mai 2026",
      due_in: -12,
      severity: "high",
      stage: "done",
    },
    {
      id: "AUD-2026-009",
      subject_fr: "Abus de marché (MAR) — Trading desk",
      subject_en: "Market abuse (MAR) — Trading desk",
      jurisdictions: ["eu", "uk"],
      regulators: ["ESMA", "FCA"],
      status: "closed",
      progress: 100,
      owner: "L. Brunner",
      due: "30 avril 2026",
      due_in: -28,
      severity: "low",
      stage: "done",
    },
  ],

  // Sample regulations for the Regulatory Framework agent
  regulations: {
    aml: [
      { jur: "ch", code: "LBA / OBA-FINMA", fr: "Loi sur le blanchiment d'argent",
        en: "Anti-Money Laundering Act", updated: "2024-03-01", severity: "critical" },
      { jur: "sg", code: "MAS 626", fr: "Notice 626 — Prévention du blanchiment et du financement du terrorisme",
        en: "Notice 626 — AML/CFT Prevention", updated: "2023-11-12", severity: "critical" },
      { jur: "hk", code: "AMLO Cap. 615", fr: "Ordonnance AML",
        en: "Anti-Money Laundering Ordinance", updated: "2023-06-30", severity: "high" },
      { jur: "eu", code: "AMLD 6 / AMLR", fr: "6e directive AML & règlement",
        en: "6th AML Directive & Regulation", updated: "2024-05-30", severity: "critical" },
      { jur: "uk", code: "MLR 2017", fr: "Money Laundering Regulations 2017",
        en: "Money Laundering Regulations 2017", updated: "2023-09-01", severity: "high" },
      { jur: "bs", code: "POCA 2018", fr: "Loi sur les produits du crime",
        en: "Proceeds of Crime Act 2018", updated: "2022-12-15", severity: "medium" },
    ],
  },

  // Sample findings for the Report agent
  findings: [
    { sev: "critical", title_fr: "Données KYC obsolètes pour 4% des clients PEP",
      title_en: "Outdated KYC data for 4% of PEP clients",
      jur: ["ch", "sg"],
      desc_fr: "127 clients politiquement exposés présentent des données de revue dépassant 18 mois.",
      desc_en: "127 politically-exposed clients have review data older than 18 months.",
    },
    { sev: "high", title_fr: "Procédure d'escalade non documentée",
      title_en: "Undocumented escalation procedure",
      jur: ["sg"],
      desc_fr: "Le mécanisme d'escalade vers le MLRO n'est pas formalisé.",
      desc_en: "Escalation to the MLRO is not formally documented.",
    },
    { sev: "medium", title_fr: "Échantillonnage de transactions non randomisé",
      title_en: "Non-randomised transaction sampling",
      jur: ["ch"],
      desc_fr: "La sélection des transactions à revoir suit un schéma déterministe.",
      desc_en: "Transaction selection follows a deterministic pattern.",
    },
    { sev: "low", title_fr: "Format des rapports SAR non harmonisé",
      title_en: "SAR report format not harmonised",
      jur: ["sg", "hk"],
      desc_fr: "Les rapports SAR utilisent deux templates différents.",
      desc_en: "SAR reports use two different templates.",
    },
  ],

  agents: [
    { id: "agent1", icon: "📋", color: "#22d3a5",
      title_key: "agent1_title", desc_key: "agent1_desc" },
    { id: "agent2", icon: "🗺", color: "#4f7ef8",
      title_key: "agent2_title", desc_key: "agent2_desc" },
    { id: "agent3", icon: "📊", color: "#a78bfa",
      title_key: "agent3_title", desc_key: "agent3_desc" },
  ],

  // Generated documents
  documents: [
    { id: "D-014-a", name: "AUD-2026-014_cadre_reglementaire.docx",
      audit: "AUD-2026-014", type: "Word", size: "284 KB",
      date: "27 mai 2026", status: "approved" },
    { id: "D-014-b", name: "AUD-2026-014_plan_audit.pptx",
      audit: "AUD-2026-014", type: "PowerPoint", size: "1.4 MB",
      date: "28 mai 2026", status: "approved" },
    { id: "D-014-c", name: "AUD-2026-014_procedures.xlsx",
      audit: "AUD-2026-014", type: "Excel", size: "612 KB",
      date: "28 mai 2026", status: "review" },
    { id: "D-013-a", name: "AUD-2026-013_rapport_final.docx",
      audit: "AUD-2026-013", type: "Word", size: "892 KB",
      date: "26 mai 2026", status: "review" },
    { id: "D-010-a", name: "AUD-2026-010_rapport_final.docx",
      audit: "AUD-2026-010", type: "Word", size: "1.1 MB",
      date: "15 mai 2026", status: "approved" },
    { id: "D-009-a", name: "AUD-2026-009_rapport_final.docx",
      audit: "AUD-2026-009", type: "Word", size: "740 KB",
      date: "30 avril 2026", status: "approved" },
  ],

  // Activity feed
  activity: [
    { who: "Agent 3", what_fr: "Rapport généré pour AUD-2026-013",
      what_en: "Report generated for AUD-2026-013", ago: "12 min", icon: "📊" },
    { who: "L. Brunner", what_fr: "Recommandation approuvée (AUD-2026-014)",
      what_en: "Recommendation approved (AUD-2026-014)", ago: "1 h", icon: "✓" },
    { who: "Agent 2", what_fr: "Plan d'audit mis à jour (AUD-2026-014)",
      what_en: "Audit plan updated (AUD-2026-014)", ago: "3 h", icon: "🗺" },
    { who: "Agent 1", what_fr: "Cadre AML compilé (AUD-2026-012)",
      what_en: "AML framework compiled (AUD-2026-012)", ago: "1 j", icon: "📋" },
    { who: "Système", what_fr: "AUD-2026-010 clôturé",
      what_en: "AUD-2026-010 closed", ago: "13 j", icon: "🔒" },
  ],
};
