[theme]
base = "dark"
primaryColor = "#4f7ef8"
backgroundColor = "#070b14"
secondaryBackgroundColor = "#0e0e0e"
textColor = "#f0f0f0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
